{{ if .Values.zerossl.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl-prod
spec:
  acme:
    email: {{ .Values.email }}
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: {{ .Values.zerossl.eabKeyId | quote }}
      keySecretRef:
        name: zerossl-eab
        key: eab-hmac-key
    privateKeySecretRef:
      name: zerossl-prod
    solvers:
      - http01:
          ingress:
            class: nginx
{{ end }}
