apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-{{ .Values.apps.suffix }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-{{ .Values.apps.suffix }}
  source:
    repoURL: 'https://moreirodamian.github.io/helm-charts/'
    targetRevision: 4.6.3
    chart: ingress-nginx
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: ingress-nginx.controller.service.annotations.service\.beta\.kubernetes\.io/do-loadbalancer-name
          value: {{ .Values.ingress.loadbalancerName }}
        - name: ingress-nginx.controller.service.annotations.service\.beta\.kubernetes\.io/do-loadbalancer-hostname
          value: {{ .Values.ingress.loadbalancerName }}
      {{ if .Values.ingress.doProxyProtocol.enabled }}
        - name: ingress-nginx.controller.service.annotations.service\.beta\.kubernetes\.io/do-loadbalancer-enable-proxy-protocol
          value: "true"
      {{ end }}
{{/*        - name: ingress-nginx.controller.metrics.enabled*/}}
{{/*        - value: "true"*/}}
{{/*        - name: ingress-nginx.controller.podAnnotations.prometheus\.io/scrape*/}}
{{/*          value: "true"*/}}
{{/*        - name: ingress-nginx.controller.podAnnotations.prometheus\.io/port*/}}
{{/*          value: "10254"*/}}
  destination:
    namespace: nginx-ingress
    name: {{ .Values.apps.destination.name }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true