{{ if .Values.apps.ingress.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-{{ .Values.apps.suffix }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  {{ if .Values.apps.project }}
  project: {{ .Values.apps.project }}
  {{ else }}
  project: infra-{{ .Values.apps.suffix }}
  {{ end }}
  source:
    repoURL: 'https://moreirodamian.github.io/helm-charts/'
    targetRevision: 5.0.2
    chart: ingress-nginx
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: ingress-nginx.controller.service.annotations.service\.beta\.kubernetes\.io/do-loadbalancer-type
          value: "REGIONAL"
        - name: ingress-nginx.controller.service.annotations.service\.beta\.kubernetes\.io/do-loadbalancer-name
          value: {{ .Values.ingress.loadbalancerName }}
        - name: ingress-nginx.controller.service.annotations.service\.beta\.kubernetes\.io/do-loadbalancer-hostname
          value: {{ .Values.ingress.loadbalancerName }}
      {{ if .Values.ingress.doProxyProtocol.enabled }}
        - name: ingress-nginx.controller.service.annotations.service\.beta\.kubernetes\.io/do-loadbalancer-enable-proxy-protocol
          value: "true"
      {{ end }}
      {{- range $port, $service := .Values.ingress.tcp }}
        - name: ingress-nginx.tcp.{{ $port }}
          value: "{{ $service }}"
      {{- end }}
      {{- range $port, $service := .Values.ingress.udp }}
        - name: ingress-nginx.udp.{{ $port }}
          value: "{{ $service }}"
      {{- end }}
  destination:
    namespace: nginx-ingress
    name: {{ .Values.apps.destination.name }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
{{ end }}