apiVersion: v2
name: laravel
description: A Helm chart for Kubernetes
type: application
version: 1.1.6
dependencies:
  - name: fpm
    version: 0.1.3
  - name: web-server
    version: 0.1.2
  - name: cron
    version: 0.1.0
  - name: queue
    version: 0.1.0