apiVersion: v2
name: laravel
description: A Helm chart for Kubernetes
type: application
version: 1.1.6
dependencies:
  - name: fpm
    version: 0.1.4
  - name: web-server
    version: 0.1.3
  - name: cron
    version: 0.1.1
  - name: queue
    version: 0.1.1