apiVersion: v2
name: laravel
description: A Helm chart for Kubernetes
type: application
version: 1.1.12
dependencies:
  - name: fpm
    version: 0.1.5
  - name: web-server
    version: 0.1.4
  - name: cron
    version: 0.1.2
  - name: queue
    version: 0.1.2
  - name: sealed-secret
    version: 0.1.4
    repository: https://moreirodamian.github.io/helm-charts/