apiVersion: v2
name: laravel
description: A Helm chart for Kubernetes
type: application
version: 1.1.18
dependencies:
  - name: fpm
    version: 0.1.*
  - name: web-server
    version: 0.1.*
  - name: cron
    version: 0.1.*
    condition: cron.create
  - name: queue
    version: 0.1.*
    condition: queue.create
  - name: sealed-secret
    version: 0.1.*
    repository: https://moreirodamian.github.io/helm-charts/
    condition: sealed-secret.create