{{- if .Values.dockerSecret.encryptedData -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-{{ template "name" . }}
  labels:
    {{ include "common-labels" . | nindent 4 }}
  {{- with .Values.dockerSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  {{- with .Values.dockerSecret.encryptedData  }}
  encryptedData:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      name: docker-{{ template "name" . }}
      labels:
        {{ include "common-labels" . | nindent 8 }}
      {{- with .Values.dockerSecret.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    type: kubernetes.io/dockerconfigjson
{{- end }}
