{{- if .Values.hpa.create -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "common-labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.hpa.max_replicas }}
  minReplicas: {{ .Values.hpa.min_replicas }}
  scaleTargetRef:
    {{- if .Values.rollout -}}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    {{- else }}
    apiVersion: apps/v1
    kind: Deployment
    {{- end }}
    name: {{ template "name" . }}
  metrics:
      {{- if .Values.hpa.cpu_percentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.cpu_percentage }}
      {{- end }}
      {{- if .Values.hpa.memory_percentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.memory_percentage }}
      {{- end }}
{{- end }}