{{- if .Values.hpa.create -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "common-labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  scaleTargetRef:
    {{ if .Values.rollout }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    {{ else }}
    apiVersion: apps/v1
    kind: Deployment
    {{ end }}
    name: {{ template "name" . }}
  metrics:
      {{- if .Values.hpa.cpuPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.cpuPercentage }}
      {{- end }}
      {{- if .Values.hpa.memoryPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.memoryPercentage }}
      {{- end }}
{{- end }}