{{ if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "name" . }}
{{/*  namespace: {{ .Release.Namespace }}*/}}
  labels:
    {{ include "common-labels" . | nindent 4 }}
  {{- with .Values.sealedSecrets.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  {{- with .Values.sealedSecrets.encryptedData  }}
  encryptedData:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      name: {{ template "name" . }}
      {{/*  namespace: {{ .Release.Namespace }}*/}}
      labels:
        {{ include "common-labels" . | nindent 8 }}
      {{- with .Values.sealedSecrets.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{ if .Values.sealedSecrets.type }}
    type: {{ .Values.sealedSecrets.type }}
    {{ end }}
{{ end }}