
{{- if .Values.service.create }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "common-labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{ include "common-labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- with .Values.service.additionalPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}

{{- if .Values.ingress.externalUrl }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}-external
spec:
  type: ExternalName
  externalName: {{ .Values.ingress.externalUrl }}
{{- end }}

