{{/*{{- if index .Values "external-secrets" "version" }}*/}}
{{/*apiVersion: argoproj.io/v1alpha1*/}}
{{/*kind: Application*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Values.env }}-{{ .Values.region }}-external-secrets-operator*/}}
{{/*  namespace: argocd*/}}
{{/*  labels:*/}}
{{/*    app.kubernetes.io/name: external-secrets-operator*/}}
{{/*    app.kubernetes.io/part-of: infra*/}}
{{/*    app.kubernetes.io/env: {{ .Values.env }}*/}}
{{/*spec:*/}}
{{/*  project: infra*/}}
{{/*  destination:*/}}
{{/*    name: {{ .Values.clusterName }}*/}}
{{/*    namespace: infra*/}}
{{/*  source:*/}}
{{/*    repoURL: https://charts.external-secrets.io*/}}
{{/*    chart: external-secrets*/}}
{{/*    targetRevision: {{ index .Values "external-secrets" "version" }}*/}}
{{/*    helm:*/}}
{{/*      values: |*/}}
{{/*        {{- index .Values "external-secrets" "values" | toYaml | nindent 8 }}*/}}
{{/*  syncPolicy:*/}}
{{/*    automated:*/}}
{{/*      prune: true*/}}
{{/*      selfHeal: true*/}}
{{/*{{- end }}*/}}