{{/*{{- if index .Values "fluent-bit" "version" }}*/}}
{{/*apiVersion: argoproj.io/v1alpha1*/}}
{{/*kind: Application*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Values.env }}-{{ .Values.region }}-fluent-bit*/}}
{{/*  namespace: argocd*/}}
{{/*  labels:*/}}
{{/*    app.kubernetes.io/name: fluent-bit*/}}
{{/*    app.kubernetes.io/part-of: infra*/}}
{{/*    app.kubernetes.io/env: {{ .Values.env }}*/}}
{{/*spec:*/}}
{{/*  project: infra*/}}
{{/*  destination:*/}}
{{/*    name: {{ .Values.clusterName }}*/}}
{{/*    namespace: infra*/}}
{{/*  source:*/}}
{{/*    repoURL: https://aws.github.io/eks-charts*/}}
{{/*    chart: aws-for-fluent-bit*/}}
{{/*    targetRevision: {{ index .Values "fluent-bit" "version" }}*/}}
{{/*    helm:*/}}
{{/*      values: |*/}}
{{/*        {{- index .Values "fluent-bit" "values" | toYaml | nindent 8 }}*/}}
{{/*  syncPolicy:*/}}
{{/*    automated:*/}}
{{/*      prune: true*/}}
{{/*      selfHeal: true*/}}
{{/*{{- end }}*/}}