{{- if index .Values "metrics-server" "version" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.env }}-{{ .Values.region }}-metrics-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/part-of: {{ .Values.project }}
    app.kubernetes.io/env: {{ .Values.env }}
spec:
  project: {{ .Values.project }}
  destination:
    name: {{ .Values.clusterName }}
    namespace: {{ .Values.namespace }}
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    chart: metrics-server
    targetRevision: {{ index .Values "metrics-server" "version" }}
    helm:
      values: |
        {{- index .Values "metrics-server" "values" | toYaml | nindent 8 }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
{{- end }}