{{- if index .Values "prometheus" "version" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.env }}-{{ .Values.region }}-prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  source:
    repoURL: 'https://moreirodamian.github.io/helm-charts/'
    targetRevision: {{ index .Values "prometheus" "version" }}
    chart: prometheus
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: "kube-prometheus-stack.prometheus.prometheusSpec.remoteWrite[0].url"
          value: {{ .Values.prometheus.remoteWrite.url }}
        - name: "kube-prometheus-stack.prometheus.prometheusSpec.remoteWrite[0].basicAuth.username.name"
          value: {{ .Values.prometheus.remoteWrite.secret.name }}
        - name: "kube-prometheus-stack.prometheus.prometheusSpec.remoteWrite[0].basicAuth.username.key"
          value: "username"
        - name: "kube-prometheus-stack.prometheus.prometheusSpec.remoteWrite[0].basicAuth.password.name"
          value: {{ .Values.prometheus.remoteWrite.secret.name }}
        - name: "kube-prometheus-stack.prometheus.prometheusSpec.remoteWrite[0].basicAuth.password.key"
          value: "password"
        - name: "alertmanager.enabled"
          value: "false"
        - name: "grafana.enabled"
          value: "false"
        - name: "sealed-secret.name"
          value: {{ .Values.prometheus.remoteWrite.secret.name }}
        - name: "sealed-secret.encryptedData.username"
          value: {{ .Values.prometheus.remoteWrite.secret.username }}
        - name: "sealed-secret.encryptedData.password"
          value:  {{ .Values.prometheus.remoteWrite.secret.password }}
        - name: "sealed-secret.namespace"
          value: {{ {{ .Values.namespace }} }}
        - name: "kube-prometheus-stack.prometheus.prometheusSpec.externalLabels.cluster"
          value: {{ .Values.prometheus.clusterName }}

  destination:
    name: {{ .Values.clusterName }}
    namespace: {{ .Values.namespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
{{- end }}