apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.name }}
  namespace: {{ .Values.global.namespace | default .Values.namespace}}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  {{- with .Values.encryptedData  }}
  encryptedData:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      name: {{ .Values.name }}
      namespace: {{ .Values.global.namespace | default .Values.namespace}}
      creationTimestamp: null
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{ if .Values.type }}
    type: {{ .Values.type }}
    {{ end }}