apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.name }}
spec:
  {{- with .Values.encryptedData  }}
  encryptedData:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      name: {{ .Values.name }}
