serviceAccount:
  create: false
  annotations: {}
  name: ""
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 80
    targetPort: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16m
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
  hosts: []
  tls: []

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

Release:
  Name: ''

testConnection:
  enabled: false

service:
  type: ClusterIP
  port: 80
  targetPort: 80

deployment:
  resources: {}
  replicaCount: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  env: {}

image:
  pullPolicy: IfNotPresent

nameOverride : ''