{{- if .Values.global.dockerSecret.name -}}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.global.dockerSecret.key }}
kind: Secret
metadata:
   name: {{ .Values.global.dockerSecret.key }}
   namespace: {{ .Values.global.namespace | default .Values.namespace}}
type: kubernetes.io/dockerconfigjson
{{ -end }}