apiVersion: v1
kind: Service
metadata:
  name: {{ include "fpm.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Values.namespace}}
  labels:
    {{- include "fpm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "fpm.selectorLabels" . | nindent 4 }}
