{{- if .Values.global.dockerSecret.name -}}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.global.dockerSecret.key }}
kind: Secret
metadata:
   name: {{ .Values.global.dockerSecret.name }}
   namespace: {{ .Values.global.namespace | default .Values.namespace}}
   annotations:
     "helm.sh/hook-weight": "-5"
type: kubernetes.io/dockerconfigjson
{{- end }}