{{/*apiVersion: apps/v1*/}}
{{/*kind: Deployment*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "fpm.fullname" . }}*/}}
{{/*  namespace: {{ .Values.global.namespace | default .Values.namespace}}*/}}
{{/*  labels:*/}}
{{/*    {{- include "fpm.labels" . | nindent 4 }}*/}}
{{/*spec:*/}}
{{/*  {{- if not .Values.autoscaling.enabled }}*/}}
{{/*  replicas: {{ .Values.deployment.replicaCount }}*/}}
{{/*  {{- end }}*/}}
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      {{- include "fpm.selectorLabels" . | nindent 6 }}*/}}
{{/*  template:*/}}
{{/*    metadata:*/}}
{{/*      {{- with .Values.podAnnotations }}*/}}
{{/*      annotations:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
{{/*      labels:*/}}
{{/*        {{- include "fpm.selectorLabels" . | nindent 8 }}*/}}
{{/*    spec:*/}}
{{/*      {{- with .Values.global.imagePullSecrets }}*/}}
{{/*      imagePullSecrets:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
{{/*      serviceAccountName: {{ include "fpm.serviceAccountName" . }}*/}}
{{/*      securityContext:*/}}
{{/*        {{- toYaml .Values.podSecurityContext | nindent 8 }}*/}}
{{/*      containers:*/}}
{{/*        - name: {{ .Chart.Name }}*/}}
{{/*          securityContext:*/}}
{{/*            {{- toYaml .Values.securityContext | nindent 12 }}*/}}
{{/*          image: {{ include "fpm.image" .}}*/}}
{{/*          imagePullPolicy: {{ .Values.image.pullPolicy }}*/}}
{{/*          ports:*/}}
{{/*            - name: http*/}}
{{/*              containerPort: {{ .Values.service.port }}*/}}
{{/*              protocol: TCP*/}}
{{/*          {{- with .Values.deployment.probes }}*/}}
{{/*          livenessProbe:*/}}
{{/*            {{- toYaml . | nindent 12 }}*/}}
{{/*          {{- end }}*/}}
{{/*          resources:*/}}
{{/*            {{- toYaml .Values.deployment.resources | nindent 12 }}*/}}
{{/*          {{- with .Values.deployment.volumeMounts }}*/}}
{{/*          volumeMounts:*/}}
{{/*            {{- toYaml . | nindent 12 }}*/}}
{{/*          {{- end }}*/}}
{{/*          {{- with .Values.deployment.lifecycle }}*/}}
{{/*          lifecycle:*/}}
{{/*            {{- toYaml . | nindent 12 }}*/}}
{{/*          {{- end }}*/}}
{{/*          {{- with .Values.deployment.envFrom }}*/}}
{{/*          envFrom:*/}}
{{/*            {{- toYaml . | nindent 12 }}*/}}
{{/*          {{- end }}*/}}
{{/*          {{- with .Values.deployment.env }}*/}}
{{/*          env:*/}}
{{/*            {{- toYaml . | nindent 12 }}*/}}
{{/*          {{- end }}*/}}
{{/*      {{- with .Values.deployment.volumes }}*/}}
{{/*      volumes:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
{{/*      {{- with .Values.deployment.nodeSelector }}*/}}
{{/*      nodeSelector:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
{{/*      {{- with .Values.deployment.affinity }}*/}}
{{/*      affinity:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
{{/*      {{- with .Values.deployment.tolerations }}*/}}
{{/*      tolerations:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
{{ if .Values.migrations.enabled }}


apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fpm.fullnameMigrations" . }}
  namespace: {{ .Values.global.namespace | default .Values.namespace}}
  labels:
    {{- include "fpm.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "fpm.fullnameMigrations" . }}
      labels:
      {{- include "fpm.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: laravel-migrate
          image: {{ include "fpm.imageMigrations" .}}
          {{- with .Values.migrations.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.migrations.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.env }}
          env:
          {{- toYaml . | nindent 12 }}
        {{- end }}
{{ end }}