serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


Release:
  Name: ''

testConnection:
  enabled: false

migrations:
  enabled: true
  command: [ "/bin/sh","-c" ]
  args: [ (php artisan migrate --force || true) ]
  image:
    component: cli

deployment:
  resources: {}
  volumeMounts: {}
  lifecycle: {}
  replicaCount: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  envFrom: {}
  volumes: {}
  persistentVolumeClaim:
    enabled: false
    storageClassName: "nfs"
    accessModes:
      - ReadWriteMany
    size: "100Mi"
    mountPath: "/var/www/html/storage"
image:
  pullPolicy: IfNotPresent
  component: fpm

config: {}
secrets: {}
